version: 2.1
jobs:
  build_and_render:
    docker:
      - image: fpco/stack-build:lts-14.19
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - build-cache-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: make cisetup
      - run:
          name: Run tests
          command: make citest
      - run:
          name: Generate docs
          command: make cidocs
      - run:
          name: Compress docs
          command: make cicompress
      - save_cache:
          name: Cache Dependencies
          key: build-cache-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - store_artifacts:
          path: /tmp/haddock.tar.gz
workflows:
  version: 2
  build_and_render:
    jobs:
      - build_and_render
